
package project1;

/**
* This class is used as an about JDialog for Future Annuity. It includes a constructor
* that accepts two parameters: the parent frame, and a boolean for the modality
* <p>
* <b>Class:</b>         About
 <p>
* <b>File:</b>          About.java
 <p>
* <b>Environment:</b>   PC, Windows 10, JDK 1.8.0_151, NetBeans 8.2
* <p>
* <b>Date:</b>          1/24/2018 
* <p>
* @author               Koenn Becker
* @version              1.0.0
* @see                  project1.FutureAnnuity
*/ 
public class About extends javax.swing.JDialog {

    /**        
    * <b>Constructor:</b>   About
    * <p>
    * <b>Description:</b>   Calls the initComponents() method to initialize GUI components<br>
    *                       Centers the JDialog and sets its default button to closeJButton
    * <p>
    * <b>Date Created:</b>  1/24/2018   
    * <p>
    * @author               Koenn Becker
    * @param                parent The parent frame
    * @param                modal True or false is modaless or not
    */
    public About(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.setLocationRelativeTo(null);       // Centers aboutJDialog
        this.getRootPane().setDefaultButton(closeJButton);  // Sets close to default button on About dialog
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aboutJLabel = new javax.swing.JLabel();
        detailsJLabel = new javax.swing.JLabel();
        formulaPicJLabel = new javax.swing.JLabel();
        closeJButton = new javax.swing.JButton();
        copyrightJLabel = new javax.swing.JLabel();
        aboutJScrollPane = new javax.swing.JScrollPane();
        aboutJTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About--Future Annuity");
        setPreferredSize(new java.awt.Dimension(424, 630));
        setSize(new java.awt.Dimension(426, 630));
        setType(java.awt.Window.Type.UTILITY);

        aboutJLabel.setFont(new java.awt.Font("Helvetica", 1, 36)); // NOI18N
        aboutJLabel.setForeground(new java.awt.Color(229, 152, 88));
        aboutJLabel.setText("About");

        detailsJLabel.setText("<html><h2>Version: 1.0.0</h2><h2>Developed by: Koenn Becker - 2018</h2></html>");

        formulaPicJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/formula.png"))); // NOI18N
        formulaPicJLabel.setPreferredSize(new java.awt.Dimension(272, 189));
        formulaPicJLabel.setRequestFocusEnabled(false);

        closeJButton.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        closeJButton.setMnemonic('R');
        closeJButton.setText("Close");
        closeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeJButtonActionPerformed(evt);
            }
        });

        copyrightJLabel.setText("Copyright © Koenn Becker");

        aboutJTextArea.setEditable(false);
        aboutJTextArea.setColumns(20);
        aboutJTextArea.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        aboutJTextArea.setLineWrap(true);
        aboutJTextArea.setRows(5);
        aboutJTextArea.setText("An annuity is a sum of money that is paid in regular equal payments.\n\nThis program calculates the annuity of an account that has a fixed interest rate. You can enter the payment you will deposit each period, the interest rate of your account, the number of compounds a year, and the number of years you plan on maturing the annuity. Below is the formula used in this calculation:\n\nA = annuity\nP = payments\nr = interest\nt = years\n\nThanks to Marty Hall for PrintUtilities, enabling us to print!");
        aboutJTextArea.setWrapStyleWord(true);
        aboutJTextArea.setCaretPosition(0);
        aboutJScrollPane.setViewportView(aboutJTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(aboutJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addGap(166, 166, 166))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(detailsJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(formulaPicJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aboutJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(closeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(copyrightJLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(aboutJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(aboutJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formulaPicJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailsJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(copyrightJLabel)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**        
    * <b>Method:</b>        closeJButtonActionPerformed()
    * <p>
    * <b>Description:</b>   Closes the aboutJDialog using the .dispose() method
    * <p>
    * <b>Date Created:</b>  1/10/2018 
    * <p>
    * @author               Koenn Becker
    * @param                evt Unused.
    */
    private void closeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeJButtonActionPerformed
        // Closes About dialog box only
        this.dispose();
    }//GEN-LAST:event_closeJButtonActionPerformed

   /*MAIN NOT IN USE*/
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                About dialog = new About(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboutJLabel;
    private javax.swing.JScrollPane aboutJScrollPane;
    private javax.swing.JTextArea aboutJTextArea;
    private javax.swing.JButton closeJButton;
    private javax.swing.JLabel copyrightJLabel;
    private javax.swing.JLabel detailsJLabel;
    private javax.swing.JLabel formulaPicJLabel;
    // End of variables declaration//GEN-END:variables
}
