/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project1;

import java.text.DecimalFormat;

/**
 *
 * @author Koenn
 */
public class FutureAnnuity extends javax.swing.JFrame {

    /**
     * Creates new form FutureAnnuity
     */
    public FutureAnnuity() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        inputJPanel = new javax.swing.JPanel();
        paymentJLabel = new javax.swing.JLabel();
        paymentJTextField = new javax.swing.JTextField();
        rateJLabel = new javax.swing.JLabel();
        rateJSpinner = new javax.swing.JSpinner();
        numberOfPaymentsLabel = new javax.swing.JLabel();
        numberOfPaymentsJTextField = new javax.swing.JTextField();
        yearsJLabel = new javax.swing.JLabel();
        yearsJTextField = new javax.swing.JTextField();
        outputJPanel = new javax.swing.JPanel();
        annuityJLabel = new javax.swing.JLabel();
        annuityJTextField = new javax.swing.JTextField();
        totalPayJLabel = new javax.swing.JLabel();
        totalPayJTextField = new javax.swing.JTextField();
        interestJLabel = new javax.swing.JLabel();
        interestJTextField = new javax.swing.JTextField();
        calculateJButton = new javax.swing.JButton();
        buttonsJPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        JMenuBar = new javax.swing.JMenuBar();
        fileJMenu = new javax.swing.JMenu();
        clearJMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        helpJMenu = new javax.swing.JMenu();
        aboutJMenuItem = new javax.swing.JMenuItem();

        jLabel1.setText("About");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(182, 182, 182))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(257, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Future Annuity");
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        inputJPanel.setBackground(new java.awt.Color(255, 102, 0));
        inputJPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        inputJPanel.setLayout(new java.awt.GridLayout(4, 3, 10, 17));

        paymentJLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        paymentJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        paymentJLabel.setText("Periodic Payment:");
        inputJPanel.add(paymentJLabel);

        paymentJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentJTextFieldActionPerformed(evt);
            }
        });
        inputJPanel.add(paymentJTextField);

        rateJLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        rateJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rateJLabel.setText("Interest (as a %):");
        inputJPanel.add(rateJLabel);
        inputJPanel.add(rateJSpinner);

        numberOfPaymentsLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        numberOfPaymentsLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        numberOfPaymentsLabel.setText("Compunds per year:");
        inputJPanel.add(numberOfPaymentsLabel);

        numberOfPaymentsJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfPaymentsJTextFieldActionPerformed(evt);
            }
        });
        inputJPanel.add(numberOfPaymentsJTextField);

        yearsJLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        yearsJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        yearsJLabel.setText("Years:");
        inputJPanel.add(yearsJLabel);

        yearsJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearsJTextFieldActionPerformed(evt);
            }
        });
        inputJPanel.add(yearsJTextField);

        outputJPanel.setLayout(new java.awt.GridLayout(3, 2, 10, 15));

        annuityJLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        annuityJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        annuityJLabel.setText("Future Annuity Balance:");
        outputJPanel.add(annuityJLabel);

        annuityJTextField.setEditable(false);
        annuityJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annuityJTextFieldActionPerformed(evt);
            }
        });
        outputJPanel.add(annuityJTextField);

        totalPayJLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        totalPayJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalPayJLabel.setText("Total Payments:");
        outputJPanel.add(totalPayJLabel);

        totalPayJTextField.setEditable(false);
        totalPayJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalPayJTextFieldActionPerformed(evt);
            }
        });
        outputJPanel.add(totalPayJTextField);

        interestJLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        interestJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        interestJLabel.setText("Interest Earned:");
        outputJPanel.add(interestJLabel);

        interestJTextField.setEditable(false);
        interestJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interestJTextFieldActionPerformed(evt);
            }
        });
        outputJPanel.add(interestJTextField);

        calculateJButton.setBackground(new java.awt.Color(255, 204, 153));
        calculateJButton.setFont(new java.awt.Font("Alcubierre", 0, 18)); // NOI18N
        calculateJButton.setMnemonic('C');
        calculateJButton.setText("Calculate");
        calculateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateJButtonActionPerformed(evt);
            }
        });

        buttonsJPanel.setLayout(new java.awt.GridLayout(1, 3, 20, 0));

        jButton1.setFont(new java.awt.Font("Alcubierre", 0, 18)); // NOI18N
        jButton1.setMnemonic('R');
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        buttonsJPanel.add(jButton1);

        jButton2.setFont(new java.awt.Font("Alcubierre", 0, 18)); // NOI18N
        jButton2.setMnemonic('P');
        jButton2.setText("Print");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        buttonsJPanel.add(jButton2);

        jButton3.setFont(new java.awt.Font("Alcubierre", 0, 18)); // NOI18N
        jButton3.setMnemonic('Q');
        jButton3.setText("Quit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        buttonsJPanel.add(jButton3);

        fileJMenu.setMnemonic('F');
        fileJMenu.setText("File");
        fileJMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        clearJMenuItem.setText("Clear");
        clearJMenuItem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        clearJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearJMenuItemActionPerformed(evt);
            }
        });
        fileJMenu.add(clearJMenuItem);

        jMenuItem1.setMnemonic('P');
        jMenuItem1.setText("Print");
        jMenuItem1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fileJMenu.add(jMenuItem1);

        jMenuItem2.setMnemonic('Q');
        jMenuItem2.setText("Quit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        fileJMenu.add(jMenuItem2);

        JMenuBar.add(fileJMenu);

        helpJMenu.setMnemonic('H');
        helpJMenu.setText("Help");
        helpJMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        aboutJMenuItem.setMnemonic('A');
        aboutJMenuItem.setText("About");
        aboutJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutJMenuItemActionPerformed(evt);
            }
        });
        helpJMenu.add(aboutJMenuItem);

        JMenuBar.add(helpJMenu);

        setJMenuBar(JMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outputJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                    .addComponent(calculateJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonsJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(outputJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(calculateJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearJMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearJMenuItemActionPerformed

    private void aboutJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutJMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutJMenuItemActionPerformed

    private void paymentJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentJTextFieldActionPerformed

    private void numberOfPaymentsJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfPaymentsJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOfPaymentsJTextFieldActionPerformed

    private void yearsJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearsJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearsJTextFieldActionPerformed

    private void annuityJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annuityJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_annuityJTextFieldActionPerformed

    private void interestJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interestJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interestJTextFieldActionPerformed

    private void totalPayJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalPayJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalPayJTextFieldActionPerformed

    private void calculateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateJButtonActionPerformed
        // Reads inputs and stores them in variables, then applies the future annuity formula and displays the results
        
        // Variable declaration
        DecimalFormat twoDecimals = new DecimalFormat("#,##0.00");
        float payment, interest, interestTotal, compounds, years, annuity;
        
        // Read inputs and store them in above variables
        payment = Float.parseFloat(paymentJTextField.getText());
        interest = rateJSpinner.getValue();
        compounds = Float.parseFloat(numberOfPaymentsJTextField.getText());
        years = Float.parseFloat(yearsJTextField.getText());
        
        // Calculate
        interestTotal = 1 + interest / compounds - 1;
        annuity = payment * (1 + (interest / compounds) - 1) / (interest / compounds);
        
        // Display annuity in output fields
        annuityJTextField.setText(twoDecimals.format(annuity));
        interestJTextField.setText(twoDecimals.format(interestTotal));
        
        
        
        
    }//GEN-LAST:event_calculateJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Quits the application
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
         // Quits the application
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FutureAnnuity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FutureAnnuity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FutureAnnuity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FutureAnnuity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FutureAnnuity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar JMenuBar;
    private javax.swing.JMenuItem aboutJMenuItem;
    private javax.swing.JLabel annuityJLabel;
    private javax.swing.JTextField annuityJTextField;
    private javax.swing.JPanel buttonsJPanel;
    private javax.swing.JButton calculateJButton;
    private javax.swing.JMenuItem clearJMenuItem;
    private javax.swing.JMenu fileJMenu;
    private javax.swing.JMenu helpJMenu;
    private javax.swing.JPanel inputJPanel;
    private javax.swing.JLabel interestJLabel;
    private javax.swing.JTextField interestJTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTextField numberOfPaymentsJTextField;
    private javax.swing.JLabel numberOfPaymentsLabel;
    private javax.swing.JPanel outputJPanel;
    private javax.swing.JLabel paymentJLabel;
    private javax.swing.JTextField paymentJTextField;
    private javax.swing.JLabel rateJLabel;
    private javax.swing.JSpinner rateJSpinner;
    private javax.swing.JLabel totalPayJLabel;
    private javax.swing.JTextField totalPayJTextField;
    private javax.swing.JLabel yearsJLabel;
    private javax.swing.JTextField yearsJTextField;
    // End of variables declaration//GEN-END:variables
}
